- name: variables
  host: local
  connection: local
  vars:
    COURSE: "devops with aws"
    DURATION: 120 HRS
    TRAINER: sivakumar
  tasks:
  - name: print the variable
    ansible.builtin.debug:
     msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"
     